### ISSUE TITLE
Solr4 not working after changing enterprise version 5.0.3

### ISSUE THREAD

**Issue by touchvignesh** [Alfresco/alfresco-sdk#463]
Ok This issue seems to me a side effect of issue #461. 
How to reproduce it 

1. Pull  AIO SDK 3.0.0 in eclipse 
2. Change Share and platform version to 5.0.3.5
3. Change edition to Enterprise 
4. run with clean install alfresco:run
5. try to login with share and alfresco still produces community stack which is already reported (#461) - Issue no 1. 
6. Now change the corresponding wars in local maven repo directly and do a clean -PPurge 
7. Here It says purge profile is not available and so it cleans up only target folder (This is another issue no 2)
8. Now manually delete alf_data folder and do a restart with same command described on step 4. 
9. Alfresco starts up clean but login into share shows red mark under tags in the repository page. Dashboard shows error displaying item in the recent items dashlet.
10. Solr web.xml is not getting having security lines commented out in the target folder.
11. This looks to be due to a check we have on commentOutSecureCommsInPlatformWebXml() function in AbstractRunMojo.java where it still consider the version to be > 5.1 and so replacer have never ran.

Work around
update web.xml by commenting out the lines by unzipping the war and pack it again keep it in maven local for the sdk to pick it up.

I can confirm it works after doing above step. Hope the fix for issue #461 fixes this issue as well which we should regress.

**Comment by ohej** [comment]
We have just committed the final fix for #461, which should solve the majority of this issue.

However, I have tried to reproduce the error you are seeing. I tried creating a 3.0.0 project, set version to 5.0.3.5, and surely enough because of #461 it brought up community edition. However, Solr worked as expected.

I also tried overriding my local artifacts to force it to use enterprise, but did not see the issues, no red bars in Share, and verified that tracking works as expected.

On top of that I see multiple issues reported in here:
No purge profile: Yes, since we no longer have a parent pom, no profiles are present. The only thing the purge profile does is to remove the `alf_data_dir` directory. Due popular request, this will be added as a goal in the `alfresco-maven-plugin` to address this in a later release.

Community logo displayed in login: I believe this is a known bug, and I've searched high and low for the JIRA that describes it, but I haven't been able to find it. This has no practical impact, once logged in the footer will display that it is indeed enterprise. This bug is only present in 5.0.x, I have not seen it in 5.1 or 5.2.

We are about to release SDK 3.0.1, can I ask that you re-test the Solr issue once 3.0.1 is available? I will give an update here once it's out.

**Comment by touchvignesh** [comment]
@ohej Will regress with 3.0.1 and confirm it.

**Comment by touchvignesh** [comment]
@ohej I just tested with 3.0.1 and can confirm that no solr issue. Except login screen still shows community but after login dashboard logo all shows Alfresco One. Tried with Alfresco Enterprise 5.0.3.5.

**Comment by ohej** [comment]
Closing as this was fixed in #461
